const STORAGE_KEY='ddc_phase1_state_v1';
const defaultState={points:250,chucked:0,actions:0,lessonsWatched:0,dailyWatched:false,dailyDone:false,followingHot:false,rewards:[],lessonState:{},crewSent:false};
let state=loadState();
let currentCourse=0,currentLesson=0,wingTone='honest';

const courses=[
 {title:'UNFUCK YOUR THINKING',desc:'Question the bullshit you never agreed to in the first place.',lessons:[
  {title:'YOU’RE RUNNING CODE YOU DIDN’T WRITE',time:'4 min',take:'A lot of your “normal” was installed before you were old enough to question shit.',body:'Job. House. Marriage. Status. Approval. Be normal. Don’t fail publicly. Some of that may be useful. Some of it may be somebody else’s crap wearing your voice. The problem isn’t that you were programmed. The problem is never checking the fucking code.',q:'What is the DDC move when a rule feels “normal”?',opts:['Obey it because everybody does','Question where it came from','Burn every rule automatically'],answer:1,action:'CATCH ONE “SHOULD”',actionBody:'Write one thing you think you should do. Ask: who told me this, do I actually believe it, and would I still want it if nobody could see me do it?'},
  {title:'FIND THE SCRIPT',time:'5 min',take:'“Should” is often where the programming hides.',body:'Listen for “supposed to,” “at my age,” “everybody does,” and “what will people think?” That’s usually the script peeking out from under the rug.',q:'Best first question when you notice a “should”?',opts:['Who told me this?','How do I obey faster?','How do I make it look impressive?'],answer:0,action:'CATCH THREE SCRIPTS',actionBody:'For one day, write down three “should” thoughts. Don’t fix them. Just catch the little bastards.'},
  {title:'FAMILIAR ISN’T FUCKING TRUE',time:'4 min',take:'You can repeat bullshit long enough that it starts sounding wise.',body:'“I’m too old.” “Nobody will like the real me.” “Success means money.” Maybe. Or maybe you’ve heard it so many times your brain stopped checking the receipt.',q:'A belief repeated for years is:',opts:['Automatically true','Still a belief until reality supports it','Basically science'],answer:1,action:'QUESTION ONE OLD STORY',actionBody:'Pick one belief you’ve carried forever. Write what evidence would actually prove or disprove it.'},
  {title:'THE DDC TEST',time:'6 min',take:'Is it true? Is it mine? Does it help? Can I test it? What if I’m wrong?',body:'This is where DDC stops being “I don’t give a fuck” and becomes “I give the right fucks.” You are not replacing one rigid rule with another. You are checking your shit.',q:'Which question belongs in the DDC Test?',opts:['Will strangers approve?','Can I test it?','Will this make me look successful?'],answer:1,action:'RUN THE FIVE-QUESTION TEST',actionBody:'Take one belief that keeps bothering you and answer all five questions. No TED Talk. Just answer them.'},
  {title:'RUN THE FUCKING EXPERIMENT',time:'5 min',take:'Reality beats rehearsing the same thought for six months.',body:'Go alone. Wear the thing. Take the trip. Ask the question. Try the class. Maybe it works. Maybe it blows. Either way, now you know something instead of mentally masturbating over possibilities.',q:'DDC prefers:',opts:['Endless certainty first','Small real-world experiments','Waiting until fear disappears'],answer:1,action:'TEST ONE THING',actionBody:'Do one low-risk thing this week that directly tests a belief you’ve been arguing with in your head.'},
  {title:'KEEP / CHUCK / REWRITE',time:'5 min',take:'Not every rule is stupid. Some deserve keeping. Some need editing. Some need the fucking bucket.',body:'KEEP what serves you. CHUCK somebody else’s bullshit. REWRITE a useful idea that turned into a dumb rigid rule.',q:'“Everyone needs to like me” belongs where?',opts:['KEEP forever','CHUCK or REWRITE','Put it on a vision board'],answer:1,action:'SORT FIVE BELIEFS',actionBody:'Make three columns: KEEP, CHUCK, REWRITE. Put five current beliefs somewhere.'}
 ]},
 {title:'STOP ASKING PERMISSION',desc:'Other people get opinions. They do not automatically get a steering wheel.',lessons:['WHOSE OPINION COUNTS?','PEOPLE-PLEASING ISN’T KINDNESS','SAY NO WITHOUT A FUCKING NOVEL','BE YOURSELF WITHOUT BEING AN ASSHOLE','DO IT WITHOUT POLLING THE ROOM'].map(scaffold)},
 {title:'GET OFF AUTOPILOT',desc:'If every week looks the same, maybe stop driving life with cruise control on.',lessons:['DEFAULT MODE','DO SOMETHING DIFFERENT','GO ALONE','BOREDOM IS INFORMATION','BUILD MORE FIRSTS'].map(scaffold)},
 {title:'DO THE FUCKING THING',desc:'Less rehearsing. More first moves.',lessons:['WHY YOU KEEP WAITING','MAKE THE MOVE SMALLER','PERFECTION IS A DELAY TACTIC','FEAR VS INFORMATION','SHIP THE DAMN THING'].map(scaffold)},
 {title:'CARE ABOUT THE RIGHT SHIT',desc:'Not caring is not the goal. Giving the right fucks is.',lessons:['NOT CARING IS NOT THE GOAL','YOUR PEOPLE','TIME IS THE REAL CURRENCY','HANDLE WHAT MATTERS','CHUCK THE REST'].map(scaffold)},
 {title:'MONEY = FREEDOM',desc:'Money is useful as options and runway. Looking rich is a different fucking hobby.',lessons:['STATUS VS FREEDOM','THE FUCK-OFF FUND','WHAT ARE YOU BUYING?','LIFESTYLE CREEP','BUY MORE LIFE'].map(scaffold)},
 {title:'RELATIONSHIPS WITHOUT THE BULLSHIT',desc:'Connection without games, forced timelines, or turning somebody into a renovation project.',lessons:['STOP FORCING THE OUTCOME','ACTIONS VS WORDS','ACCEPT, DISCUSS, OR LEAVE','BOUNDARIES WITHOUT THEATER','REJECTION IS INFORMATION'].map(scaffold)},
 {title:'YOUR PEOPLE',desc:'Good people are worth actual effort. Stop assuming they’ll always be there.',lessons:['WHO ARE YOUR PEOPLE?','CALL THEM','BE THE FRIEND YOU WANT','SMALL CIRCLE, REAL CIRCLE','DON’T WAIT FOR THE FUNERAL'].map(scaffold)},
 {title:'BE ALONE WITHOUT BEING LONELY',desc:'Stop waiting for somebody else’s schedule before you start living.',lessons:['ALONE DOESN’T MEAN LONELY','DO IT SOLO','THE FIRST SOLO TRIP','STOP WORRYING ABOUT LOOKING WEIRD','ENJOY YOUR OWN DAMN COMPANY'].map(scaffold)},
 {title:'STOP LIVING FOR THE SHOW',desc:'Status, comparison, social media theater, and the circus of looking successful.',lessons:['WELCOME TO THE FUCKING THEATER','STATUS IS A COSTUME','WHAT DO YOU DO?','WOULD YOU WANT IT IF NOBODY SAW?','BUILD THE LIFE BEHIND THE PHOTO'].map(scaffold)},
 {title:'THE FUCK-IT BUCKET',desc:'A full system for giving the right fucks and wasting fewer on nonsense.',lessons:['WHAT DESERVES A FUCK?','CONTROL VS CONCERN','HANDLE / SCHEDULE / CHUCK','STOP FEEDING DEAD PROBLEMS','MAKE THE BUCKET A HABIT'].map(scaffold)},
 {title:'BUILD A LIFE YOU ACTUALLY LIKE',desc:'People, freedom, work, money, experiences, responsibility and meaning. Put the whole damn thing together.',lessons:['YOUR GLASSES','WHAT ACTUALLY REMAINS?','FREEDOM WITH CONSEQUENCES','YOUR VERSION OF ENOUGH','GO FUCKING LIVE'].map(scaffold)}
];

function scaffold(title){return {title,time:'5 min',take:'This lesson gets fully built from the DDC interview for this course.',body:'No generic self-help wallpaper. We will use the course interview to add your actual stories, contradictions, jokes, opinions, examples, and the shit you think people get wrong.',q:'What makes a DDC lesson worth doing?',opts:['A motivational quote','A useful idea plus a real move','More screen time'],answer:1,action:'DO ONE REAL THING',actionBody:'Take one concrete action tied to this lesson. If nothing changes outside the app, the lesson didn’t do shit.'}}
function loadState(){try{return {...defaultState,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return {...defaultState}}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));updatePointsUI()}
function addPoints(n,msg){state.points+=n;save();toast(msg||`+${n} points`)}
function levelInfo(){const p=state.points;if(p>=4000)return['DADDY LEVEL',4000,6000];if(p>=2500)return['CHAOS AGENT',2500,4000];if(p>=1200)return['UNBOTHERED',1200,2500];return['AWAKE',0,1200]}
function updatePointsUI(){document.querySelector('#pointsTop').textContent=state.points}
function toast(text){document.querySelectorAll('.toast').forEach(x=>x.remove());const t=document.createElement('div');t.className='toast';t.textContent=text;document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}
function setNav(name){document.querySelectorAll('[data-nav]').forEach(b=>{if(b.closest('.bottom-nav'))b.classList.toggle('active',b.dataset.nav===name)})}
function render(name='home'){setNav(name);window.scrollTo(0,0);const main=document.querySelector('#main');main.innerHTML='';const views={home,wingman,university,course,lesson,challenge,hotseat,bucket,daily,crew,rewards,me};(views[name]||home)(main)}

document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]');if(nav){render(nav.dataset.nav)}})
document.querySelector('.brand-wrap').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')render('home')})

function pageHead(title,sub,back='home'){return `<div class="page-head"><div><h1>${title}</h1><div class="sub">${sub}</div></div><button class="btn ghost" data-nav="${back}">Back</button></div>`}
function home(el){const lv=levelInfo(),pct=Math.min(100,Math.max(0,(state.points-lv[1])/(lv[2]-lv[1])*100));el.innerHTML=`
<div class="hero"><div class="eyebrow">TODAY</div><div class="headline">CARE ABOUT WHAT MATTERS.<br><span class="pink">CHUCK THE REST.</span></div><p class="copy">Learn something. Do something. Laugh at some bullshit. Then get off your phone and go live.</p><div class="progress"><i style="width:${pct}%"></i></div><div class="muted" style="font-size:11px;margin-top:7px">${lv[0]} · ${lv[2]-state.points} points to next level</div></div>
<div class="section-head"><h2>WHAT THE FUCK DO YOU NEED?</h2><span>Pick your poison</span></div>
<div class="grid">
 ${tile('💬','WINGMAN','What the fuck do I say?','wingman','hot')}
 ${tile('🎓','DDC UNIVERSITY','Useful shit. No guru bullshit.','university','cool')}
 ${tile('⚡','CHALLENGE MODE','Get off your ass.','challenge')}
 ${tile('🔥','HOT SEAT','Real people. Real situations.','hotseat','hot')}
 ${tile('🪣','FUCK-IT BUCKET','Handle it or chuck it.','bucket','cool')}
 ${tile('📺','DDC DAILY','Watch. Learn. Earn.','daily')}
 ${tile('👥','DDC CREW','Your tiny circle of degenerates.','crew')}
 ${tile('🏆','REWARDS','Do shit. Get cool shit.','rewards')}
 ${tile('◎','YOUR LIFE','Proof you actually did things.','me')}
</div>
<div class="card"><div class="eyebrow">DAILY FUCK YEAH</div><h3>Complete any real-world action today</h3><p class="copy">Watching shit is nice. Doing shit is better.</p></div>`}
function tile(icon,title,desc,nav,cls=''){return `<button class="tile ${cls}" data-nav="${nav}"><div class="icon">${icon}</div><b>${title}</b><p>${desc}</p></button>`}

function wingman(el){el.innerHTML=pageHead('WINGMAN','Texts · work · dating · family · awkward bullshit')+`
<textarea id="wingInput" placeholder="Paste the message or tell DDC what happened..."></textarea>
<div class="row" style="margin-top:9px">${['honest','direct','funny','nice','flirty'].map((t,i)=>`<button class="pill ${i===0?'active':''}" data-tone="${t}">${t.toUpperCase()}</button>`).join('')}</div>
<button class="btn block" id="wingGo" style="margin-top:10px">WHAT THE FUCK DO I SAY?</button><div id="wingOut"></div>`;
el.querySelectorAll('[data-tone]').forEach(b=>b.addEventListener('click',()=>{wingTone=b.dataset.tone;el.querySelectorAll('[data-tone]').forEach(x=>x.classList.toggle('active',x===b))}));el.querySelector('#wingGo').addEventListener('click',()=>{const text=el.querySelector('#wingInput').value.trim(),out=el.querySelector('#wingOut');if(!text){out.innerHTML='<div class="result pink">Give Daddy something to work with first.</div>';return}const tones={honest:'Say what you actually mean. Stop trying to engineer their reaction.',direct:'One clean sentence. Ask for clarity. Then shut up and watch what they do.',funny:'Keep it light. If you need five paragraphs, the joke is already on you.',nice:'Warm, clear, no groveling, no essay.',flirty:'Show interest without auditioning for Most Desperate Human Alive.'};out.innerHTML=`<div class="result"><b>THE READ</b><div class="copy">There may be multiple explanations. Don’t pretend you can read minds.</div></div><div class="result pink"><b>WHAT MATTERS</b><div class="copy">${tones[wingTone]}</div></div><div class="result"><b>DDC CALL</b><div class="copy">One useful move. Then get on with your fucking day.</div></div>`})}

function university(el){const started=new Set(Object.keys(state.lessonState).filter(k=>state.lessonState[k]?.watched||state.lessonState[k]?.action).map(k=>k.split('-')[0])).size;el.innerHTML=pageHead('DDC UNIVERSITY','Question the bullshit. Keep what matters.')+`<div class="card"><div class="eyebrow">PROGRESS</div><h3>${started} / 12 courses started</h3><div class="progress"><i style="width:${started/12*100}%"></i></div></div><div id="courses"></div>`;const box=el.querySelector('#courses');courses.forEach((c,i)=>{const done=c.lessons.filter((_,j)=>state.lessonState[`${i}-${j}`]?.action).length;const b=document.createElement('button');b.className='course-row';b.innerHTML=`<small>COURSE ${String(i+1).padStart(2,'0')}</small><strong>${c.title}</strong><div class="copy">${c.desc}</div><small>${done} / ${c.lessons.length} completed</small>`;b.addEventListener('click',()=>{currentCourse=i;render('course')});box.appendChild(b)})}
function course(el){const c=courses[currentCourse],done=c.lessons.filter((_,j)=>state.lessonState[`${currentCourse}-${j}`]?.action).length;el.innerHTML=pageHead(c.title,'DDC University','university')+`<div class="card"><p class="copy">${c.desc}</p><div class="progress" style="margin-top:12px"><i style="width:${done/c.lessons.length*100}%"></i></div><div class="muted" style="font-size:11px;margin-top:6px">${done} / ${c.lessons.length} completed</div></div><div id="lessons"></div>`;const box=el.querySelector('#lessons');c.lessons.forEach((l,j)=>{const s=state.lessonState[`${currentCourse}-${j}`]||{};const b=document.createElement('button');b.className='lesson-row';b.innerHTML=`<small>LESSON ${j+1} · ${l.time}</small><strong>${l.title}</strong><small>${s.action?'DONE ✓':s.watched?'IN PROGRESS':'READY'}</small>`;b.addEventListener('click',()=>{currentLesson=j;render('lesson')});box.appendChild(b)})}
function lesson(el){const c=courses[currentCourse],l=c.lessons[currentLesson],key=`${currentCourse}-${currentLesson}`;state.lessonState[key] ||= {};const s=state.lessonState[key];el.innerHTML=pageHead(l.title,c.title,'course')+`
<div class="video-box"><div><div class="play">▶</div><strong>DDC VIDEO LESSON</strong><div class="muted" style="font-size:11px">${l.time}</div><button class="btn" id="watch" style="margin-top:12px">${s.watched?'WATCHED ✓':'WATCH +20'}</button></div></div>
<div class="card"><div class="eyebrow">WRITTEN LESSON</div><h3>${l.take}</h3><p class="copy">${l.body}</p></div>
<div class="card"><div class="eyebrow">QUICK CHECK · +10</div><h3>${l.q}</h3><div id="opts"></div><div class="muted" id="qfb" style="font-size:12px;margin-top:8px"></div></div>
<div class="card"><div class="eyebrow">REAL-WORLD MOVE · +50</div><h3>${l.action}</h3><p class="copy">${l.actionBody}</p><textarea id="actionNote" placeholder="What did you actually do?">${s.note||''}</textarea><button class="btn block" id="doAction" style="margin-top:10px">${s.action?'DONE ✓':'I DID THE FUCKING THING +50'}</button></div>`;
el.querySelector('#watch').addEventListener('click',e=>{if(s.watched)return;s.watched=true;state.lessonsWatched++;addPoints(20,'Watched. +20. Watching is not the same as changing your life, champ.');e.currentTarget.textContent='WATCHED ✓'});
const ob=el.querySelector('#opts');l.opts.forEach((o,i)=>{const b=document.createElement('button');b.className='quiz-option';b.textContent=o;b.addEventListener('click',()=>{if(s.quiz)return;if(i===l.answer){s.quiz=true;b.classList.add('correct');addPoints(10,'Correct. +10. Look at you learning shit.');el.querySelector('#qfb').textContent='Yep. That’s the move.'}else{b.classList.add('wrong');el.querySelector('#qfb').textContent='Nope. Try again with less bullshit.'}});ob.appendChild(b)});
el.querySelector('#doAction').addEventListener('click',e=>{if(s.action)return;s.action=true;s.note=el.querySelector('#actionNote').value.trim();state.actions++;addPoints(50,'FUCK YEAH. +50. Real-world action wins.');e.currentTarget.textContent='DONE ✓'});save()}

function challenge(el){const missions=['Go somewhere within 10 miles you’ve never been. Take one photo.','Call somebody you keep saying you should call. Don’t text first.','Go do one thing alone you normally wait for somebody else to do with you.','Try the thing you normally dismiss without thinking.','Leave the phone behind for 30 minutes and go outside.','Make one harmless decision today without asking a single person what they think.'];el.innerHTML=pageHead('CHALLENGE MODE','Less scrolling. More stories.')+`<div class="card"><div class="eyebrow">HOW MUCH TIME?</div><div class="row" style="margin-top:8px"><button class="pill active">15 MIN</button><button class="pill">1 HOUR</button><button class="pill">TONIGHT</button><button class="pill">WEEKEND</button></div><div class="eyebrow" style="margin-top:14px">VIBE?</div><div class="row" style="margin-top:8px"><button class="pill active">SOLO</button><button class="pill">WITH SOMEONE</button><button class="pill">SURPRISE ME</button><button class="pill">SLIGHTLY STUPID</button></div></div><button class="btn blue block" id="spin" style="margin-top:10px">GIVE ME SOMETHING TO DO</button><div id="mission"></div>`;el.querySelector('#spin').addEventListener('click',()=>{const m=missions[Math.floor(Math.random()*missions.length)];el.querySelector('#mission').innerHTML=`<div class="result"><b>YOUR MISSION</b><div class="copy">${m}</div><button class="btn block" id="doneMission" style="margin-top:10px">DONE +100</button></div>`;el.querySelector('#doneMission').addEventListener('click',e=>{if(e.currentTarget.disabled)return;e.currentTarget.disabled=true;e.currentTarget.textContent='FUCK YEAH ✓';state.actions++;addPoints(100,'Challenge complete. +100.')})})}

function hotseat(el){el.innerHTML=pageHead('HOT SEAT','Vote first. See what everybody else thinks after.')+`<div class="card"><div class="eyebrow">ANONYMOUS · 2H AGO</div><h3>I hate my job. New offer pays 15% less but gives me Fridays off and remote work. What would you do?</h3><div class="grid" style="grid-template-columns:1fr 1fr"><button class="btn ghost vote">TAKE IT</button><button class="btn ghost vote">STAY</button><button class="btn ghost vote">NEGOTIATE</button><button class="btn ghost vote">NEED INFO</button></div><div id="voteOut"></div></div><div class="card"><div class="eyebrow">FOLLOW THE UPDATE</div><p class="copy">The fun part is seeing what the hell they actually did later.</p><button class="btn ghost" id="follow">${state.followingHot?'FOLLOWING ✓':'FOLLOW THIS MESS'}</button></div>`;el.querySelectorAll('.vote').forEach(b=>b.addEventListener('click',()=>{el.querySelector('#voteOut').innerHTML=`<div class="result"><b>You voted: ${b.textContent}</b><div class="copy">Community: TAKE IT 44% · NEGOTIATE 31% · STAY 17% · NEED INFO 8%</div><div class="muted" style="font-size:11px">Crowd opinion is still crowd opinion. Use your damn brain.</div></div>`}));el.querySelector('#follow').addEventListener('click',e=>{state.followingHot=true;save();e.currentTarget.textContent='FOLLOWING ✓';toast('Following this mess.')})}

function bucket(el){el.innerHTML=pageHead('FUCK-IT BUCKET','Some shit needs action. Some shit needs a bucket.')+`<textarea id="bucketText" placeholder="What bullshit is renting space in your head?"></textarea><div class="grid-3" style="margin-top:10px"><button class="btn ghost bucket" data-a="handle">HANDLE</button><button class="btn ghost bucket" data-a="later">LATER</button><button class="btn bucket" data-a="chuck">CHUCK IT</button></div><div id="bucketOut"></div>`;el.querySelectorAll('.bucket').forEach(b=>b.addEventListener('click',()=>{const t=el.querySelector('#bucketText').value.trim();if(!t){el.querySelector('#bucketOut').innerHTML='<div class="result pink">Put the bullshit in first.</div>';return}const a=b.dataset.a;const msg=a==='handle'?'This one needs action. Pick the smallest useful move and do it.':a==='later'?'Give it a real date. Until then, stop carrying it around all fucking day.':'CHUCKED. Nothing useful to do? Then stop donating attention to it.';el.querySelector('#bucketOut').innerHTML=`<div class="result ${a==='chuck'?'pink':''}"><b>DDC CALL</b><div class="copy">${msg}</div></div>`;if(a==='chuck'){state.chucked++;el.querySelector('#bucketText').value='';addPoints(10,'Chucked. +10. Move the fuck on.')}save()}))}

function daily(el){el.innerHTML=pageHead('DDC DAILY','Fresh shit every day.')+`<div class="video-box"><div><div class="play">📺</div><strong>STOP ASKING FIVE PEOPLE</strong><div class="muted" style="font-size:11px">60-second Daddy rant</div><button class="btn" id="watchDaily" style="margin-top:12px">${state.dailyWatched?'WATCHED ✓':'WATCH +10'}</button></div></div><div class="card"><div class="eyebrow">TODAY’S TAKEAWAY</div><p class="copy">If the decision is harmless and yours to make, stop assembling a fucking jury.</p></div><div class="card"><div class="eyebrow">TINY MOVE · +20</div><h3>Make one harmless decision today without polling anybody.</h3><button class="btn ghost" id="dailyDone">${state.dailyDone?'DONE ✓':'DONE +20'}</button></div>`;el.querySelector('#watchDaily').addEventListener('click',e=>{if(state.dailyWatched)return;state.dailyWatched=true;addPoints(10,'Daily watched. +10.');e.currentTarget.textContent='WATCHED ✓'});el.querySelector('#dailyDone').addEventListener('click',e=>{if(state.dailyDone)return;state.dailyDone=true;state.actions++;addPoints(20,'Tiny move done. +20. Now go be a person.');e.currentTarget.textContent='DONE ✓'})}

function crew(el){el.innerHTML=pageHead('DDC CREW','Small circle. No follower-count bullshit.')+`<div class="card"><div class="eyebrow">TONIGHT’S CREW CHALLENGE</div><h3>Everybody does something they’ve been putting off for at least a week.</h3><button class="btn block" id="crewSend">${state.crewSent?'SENT ✓':'SEND TO CREW'}</button></div><div class="card"><div class="eyebrow">CREW VOTE</div><h3>“Do I go to this thing I already don’t want to go to?”</h3><div class="grid-3"><button class="btn ghost crewVote">GO</button><button class="btn ghost crewVote">SKIP</button><button class="btn ghost crewVote">STOP ASKING 😂</button></div><div id="crewOut" class="muted" style="font-size:12px;margin-top:8px"></div></div>`;el.querySelector('#crewSend').addEventListener('click',e=>{state.crewSent=true;save();e.currentTarget.textContent='SENT ✓';toast('Sent. Now we find out who’s all talk.')});el.querySelectorAll('.crewVote').forEach(b=>b.addEventListener('click',()=>el.querySelector('#crewOut').textContent=`Vote recorded: ${b.textContent}`))}

function rewards(el){const rewards=[['DDC Sticker Pack',500],['Fuck-It Bucket Giveaway Entry',1000],['15% Merch Unlock',1500],['Secret DDC Drop Access',2500],['Points-Only Limited Shirt',4000]],lv=levelInfo();el.innerHTML=pageHead('REWARDS','Do shit. Get cool shit.')+`<div class="card"><div class="eyebrow">YOUR POINTS</div><div style="font-size:40px;font-weight:1000">${state.points}</div><div class="muted" style="font-size:12px">Level: ${lv[0]}</div></div><div id="rewardRows"></div>`;const box=el.querySelector('#rewardRows');rewards.forEach(([name,cost])=>{const unlocked=state.rewards.includes(name);const row=document.createElement('div');row.className='card reward-row';row.innerHTML=`<div><strong>${name}</strong><div class="muted" style="font-size:11px">${cost} points</div></div><button class="btn ${unlocked?'ghost':'gold'}" ${unlocked||state.points<cost?'disabled':''}>${unlocked?'UNLOCKED':state.points>=cost?'REDEEM':'LOCKED'}</button>`;row.querySelector('button').addEventListener('click',()=>{if(unlocked||state.points<cost)return;state.points-=cost;state.rewards.push(name);save();toast(`Unlocked: ${name}`);render('rewards')});box.appendChild(row)})}

function me(el){const lv=levelInfo();el.innerHTML=pageHead('YOUR LIFE, ACTUALLY LIVED','Not perfection. Receipts.')+`<div class="grid-3"><div class="stat"><strong>${state.lessonsWatched}</strong><span>LESSONS</span></div><div class="stat"><strong>${state.actions}</strong><span>ACTIONS</span></div><div class="stat"><strong>${state.chucked}</strong><span>CHUCKED</span></div></div><div class="card"><div class="eyebrow">DDC RECEIPT</div><p class="copy">${receipt()}</p></div><div class="card"><div class="eyebrow">YOUR LEVEL</div><h3>${lv[0]}</h3><p class="copy">AWAKE → UNBOTHERED → CHAOS AGENT → DADDY LEVEL</p></div><div class="callout"><b>THE POINT IS NOT TO LIVE IN THIS APP.</b><p class="copy">The app should help you think clearer, laugh more, and do more shit outside the app.</p></div>`}
function receipt(){const x=[];if(state.lessonsWatched)x.push(`watched ${state.lessonsWatched} lesson${state.lessonsWatched===1?'':'s'}`);if(state.actions)x.push(`did ${state.actions} real-world move${state.actions===1?'':'s'}`);if(state.chucked)x.push(`chucked ${state.chucked} piece${state.chucked===1?'':'s'} of bullshit`);return x.length?`So far you ${x.join(', ')}. Better than staring at inspirational shit and doing nothing.`:'You’ve only just started. Go make some shit worth tracking.'}

updatePointsUI();render('home');
